file_format: "1"
id: 5x5pad
name: 5x5pad
type: shield
url: https://github.com/MakotoKurauchi/5x5pad
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - 5x5pad_left
  - 5x5pad_right
